name: Swift Package Resolve
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Generic 🛠
      run: xcodebuild -scheme AgoraRtmKit -destination platform=macOS
    - name: Resolve Package 🎉
      run: swift package resolve